### ISSUE TITLE
#L not working correctly in Cron DayOfWeekSpec

### ISSUE THREAD

**Issue by BennyM** [spoulson/Itinerary#13]
Add this testcase to your scheduler test:        

    new ScheduleUnitTest("Last Friday of every month",
        new CronSchedule("0", "0", "*", "*", "FRI#L", TimeSpan.Zero),
        new DateTime(2012, 1, 1, 0, 0, 0), new DateTime(2012, 6, 1, 0, 0, 0),
        new TimedEvent[] {
            new TimedEvent(new DateTime(2012, 1, 27, 0, 0, 0), TimeSpan.Zero),
            new TimedEvent(new DateTime(2012, 2, 24, 0, 0, 0), TimeSpan.Zero),
            new TimedEvent(new DateTime(2012, 3, 30, 0, 0, 0), TimeSpan.Zero),
            new TimedEvent(new DateTime(2012, 4, 27, 0, 0, 0), TimeSpan.Zero),
            new TimedEvent(new DateTime(2012, 5, 25, 0, 0, 0), TimeSpan.Zero)
         }
       )

**Comment by spoulson** [comment]
SaintPeter, this is long long overdue on my part.  I merged in your fix.  Thanks for the contribution!
