### ISSUE TITLE
Every x-Thursday of the Month?

### ISSUE THREAD

**Issue by Mike-E-angelo** [spoulson/Itinerary#16]
Cool project. :)

I apologize for creating an issue here.  This is more of a question than issue (GitHub needs forums, too!).  Please feel free to close this as soon as answered.

I checked out this page: https://github.com/spoulson/Itinerary/wiki/TDL-Expression-Syntax

And the advanced samples, and I couldn't find any examples that fit what I am trying to do specifically.  I am writing a project where we will check to see if today is:
- The x-Thursday of the month.
- The x-th of every month.

Obviously, the intervals are a close match to the 2nd scenario, but we're looking for the exact day number of the month.

Is this possible with TDL syntax?

**Comment by Michael-DST** [comment]
Oh!  There it is.  It's hidden in the cron section:

First Friday of every month:
cron 0 0 * * 5#1

Or in my case:
cron 0 0 * * 4#3

Doing a little more searching on cron, I found the answer to my other question:
cron 0 0 15 * *

Of course, I find them AFTER posting here. ;)

**Comment by spoulson** [comment]
Glad you found it useful!
